stages:
  - deploy
deploy-production:
  variables:
    GIT_STRATEGY: clone
    DEPLOY_USER: $PROD_USER
    DEPLOY_PORT: $PROD_PORT
    DEPLOY_HOST: $PROD_HOST
    DEPLOY_ROOT: $PROD_ROOT
  stage: deploy
  resource_group: production
  only:
    - master
  when: manual
  script:
    - |
      ssh -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST /bin/bash -e <<EOF
        cd $DEPLOY_ROOT
        git add -A
        git reset --hard
        git pull
        composer update --no-interaction --ignore-platform-reqs
        php ~/www/bitrix/tools/migrate apply -f
        ~/sensors_server_stop.sh
        ~/sensors_server_start.sh
      EOF