<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("git");
?>git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch archive77.tar.gz" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch mysql.sql" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch __bx_log.log" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch archive.tar.gz" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch local/php_interface/cron/dekon.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad16_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad15_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad17_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad10_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad11_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad13_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad14_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad12_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad08_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad09_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad28_06_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad27_06_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad06_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad07_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad14_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad13_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad10_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad09_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad12_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad11_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad07_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad04_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad05_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad03_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad31_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad02_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad01_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad30_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad28_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad29_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad27_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad26_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad24_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad25_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad22_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad23_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad21_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad20_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad15_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad16_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad17_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad18_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad06_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad05_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad04_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad03_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad02_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad01_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad29_06_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch luminad_main/luminad30_06_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad15_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad16_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad17_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad10_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad11_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad13_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad14_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad12_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad08_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad09_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad28_06_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad27_06_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad06_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad07_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad14_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad13_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad10_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad09_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad12_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad11_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad07_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad04_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad05_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad03_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad31_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad02_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad01_08_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad30_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad28_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad29_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad27_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad26_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad24_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad25_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad22_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad23_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad21_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad20_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad15_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad16_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad17_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad18_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad05_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad06_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad04_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad03_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad02_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad01_07_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad29_06_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch vamsvet_files/luminad30_06_17.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch update_vamsvet/luminad.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch local.tar.gz" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch SxGeoCity.dat" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch sermap.xml" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch sitemap-back.xml" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch sitemap.xml" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch file.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch skidka/x00.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch file.csv" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch roistat/CRM.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch roistat/CRM.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch sitemap.xml" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch roistat/CRM.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch roistat/CRM.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch sitemap_iblock_7.xml" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch roistat/CRM.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch roistat/CRM.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch seo/SectionText.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch sitemap691.xml" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch roistat/CRM.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch sitemap_iblock_7.part1.xml" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch roistat/CRM.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch roistat/CRM.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch roistat/CRM.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch sitemap690.xml" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch sitemap_old.xml" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch sitemap.xml" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch PROXYLEAD.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch PROXYLEAD.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch PROXYLEAD.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch PROXYLEAD.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch PROXYLEAD.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch Classes/PHPExcel/Shared/PDF/fonts/dejavu-fonts-ttf-2.30/status.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch PROXYLEAD.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch PROXYLEAD.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch PROXYLEAD.txt" --prune-empty -f -- --all<br>
 git filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch PROXYLEAD.txt" --prune-empty -f -- --all<br>
git for-each-ref --format="%(refname)" refs/original/<br>
 git reflog expire --expire=now --all<br>
 git gc --aggressive --prune=now<br>
 <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>